import type { Metadata } from "next";
import { Geist, Geist_Mono, Krona_One, Poppins, Krub } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/lib/providers/TanstackQuery/QueryClient";
import { Toaster } from "sonner";
import ReduxProvider from "@/lib/providers/ReduxProvider";
import Navbar from "@/components/common/Navbar";
import LenisProvider from "@/lib/providers/lenis/LenisProvider";
import Footer from "@/components/common/Footer";
import CartSyncHandler from "@/lib/providers/CartProvider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
  style: "normal",
  fallback: ["system-ui", "sans-serif"],
});

const kronaOne = Krona_One({
  variable: "--font-krona-one",
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  preload: true,
  style: "normal",
  fallback: ["system-ui", "sans-serif"],
});

const krub = Krub({
  variable: "--font-krub",
  weight: ["300", "400"],
  subsets: ["latin"],
  display: "swap",
  preload: true,
  style: "normal",
  fallback: ["system-ui", "sans-serif"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
//   display: "swap",
//   preload: true,
//   style: "normal",
//   fallback: ["system-ui", "sans-serif"],
// });

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  preload: true,
  style: "normal",
  fallback: ["system-ui"],
});

export const metadata: Metadata = {
  title: {
    default: "Baraka Hijab",
    template: "%s | Baraka Hijab",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${geistSans.className} ${geistSans.variable} ${kronaOne.variable} ${krub.variable} ${poppins.variable} overflow-hidden antialiased`}
      >
        <Script
          src="https://app.sandbox.midtrans.com/snap/snap.js"
          // script.src = 'https://app.midtrans.com/snap/snap.js'; // Production
          data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
          strategy="beforeInteractive"
        />

        <LenisProvider>
          <ReduxProvider>
            <ReactQueryProvider>
              <CartSyncHandler />
              <Navbar />
              {children}
              <Footer />
            </ReactQueryProvider>
            <Toaster />
          </ReduxProvider>
        </LenisProvider>
      </body>
    </html>
  );
}
